[package]
name = "solana_pumpfun_comment"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"  # For JSON handling
rand = "0.8" 
